### ISSUE TITLE
GHC 8.8 support

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/flexdis86#11]
flexdis86 currently fails to build on GHC 8.8 with the following `MonadFail` related error:

```
src/Flexdis86/ByteReader.hs:74:24: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: ByteReader m
        bound by the class declaration for ‘ByteReader’
        at src/Flexdis86/ByteReader.hs:52:35-44
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            invalidInstruction :: forall a. m a
          or the class declaration for ‘ByteReader’
    • In the expression: fail "Invalid instruction"
      In an equation for ‘invalidInstruction’:
          invalidInstruction = fail "Invalid instruction"
   |
74 |   invalidInstruction = fail "Invalid instruction"
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
